version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:linux-arm64
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${DB}
      - GITEA__database__USER=${USER}
      - GITEA__database__PASSWD=${PASS}
    restart: always
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - gitea
    volumes:
      - ${DATA}/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${WEB_PORT}:3000
      - ${SSH_PORT}:22
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea-postgres
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=${DB}
    networks:
      - gitea
    volumes:
      - ${DATA}/db:/var/lib/postgresql/data
