version: '2'

networks:
  transmission:
    external: false

services:
  transmission:
    image: linuxserver/transmission:arm64v8-latest
    container_name: transmission
    environment:
      - PASS=${PASS}
      - PGID=1000
      - PUID=1000
      - TZ=${TIMEZONE}
      - USER=${USER}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ${DATA}/config:/config
      - ${STORAGE}/downloads:/downloads
      - ${DATA}/watch:/watch
    networks:
      - transmission
