version: "2.1"

networks:
  podgrab:
    external: false

services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
      - PASSWORD=${PASS}
    volumes:
      - ${DATA}/config:/config
      - ${DATA}/data:/assets
    ports:
      - ${PORT}:8080
    restart: unless-stopped
    networks:
      - podgrab
